### PR TITLE
Add TruffleRuby 1.0.0-rc13

### PR DESCRIPTION
**Pull request by eregon**
cc @havenwood 

@havenwood @postmodern Could you consider giving me write access to this repo for the purpose of adding TruffleRuby releases?
That would be convenient, and it might allow using `ruby-versions` more when adding TruffleRuby releases to other Ruby installers, by being able to merge very quickly and then query the data (e.g., hashes) from `master`.
@havenwood is quite fast to merge (thanks!), so this is not required but it would be more convenient.

### CODE REVIEW

**Comment by havenwood** [comment]
@eregon That makes sense to me. I'd be happy for you to have the commit bit.

**Comment by postmodern** [comment]
@eregon invited!

**Comment by eregon** [comment]
@postmodern Thank you!
Would you like me to create PRs for new TruffleRuby releases and then merge them, or just push directly to `master`?

**Comment by postmodern** [comment]
@eregon you can push to master, just ensure that you use the `update.sh` script and follow [CONTRIBUTING.md](https://github.com/postmodern/ruby-versions/blob/master/CONTRIBUTING.md).

**Pull request merged**
