### PR TITLE
Added latest version of SSL vulnerability fix

### PR DESCRIPTION
**Pull request by ferdinandrosario**

### CODE REVIEW

**Comment by havenwood** [comment]
Thanks! It looks like we still need `.gz` and `.bz2` extensions for 2.0.0-p645 and `.zip` and `.bz2` extensions for 2.1.6 and 2.2.2. And then MD5, SHA1 and SHA512 checksums in addition to the SHA256 ones for all of them.

We might want to also go ahead and add `.xz` extensions as well since they're shipping those now. Or we could go back and add all those later.

**Comment by havenwood** [comment]
This is closed by commits with checksums for ruby-2.2.2 2e51e0d, ruby-2.1.6 2ffcf73, ruby-2.0.0-p645 ad93634 and updated stable Ruby versions 7bd985e. Thanks!

**Comment by ferdinandrosario** [comment]
Thanks @havenwood , please help me to get all the required details so that in near feature I will add everything that you specified here. 
As of now I'm only referring https://www.ruby-lang.org/en/

**Comment by havenwood** [comment]
On the release page for each Ruby they have the `.tar.bz2`, `.tar.gz`, `.tar.xz` and `.zip` archives with SHA1, SH256 and SHA512 for each. For example: https://www.ruby-lang.org/en/news/2015/04/13/ruby-2-2-2-released/

Since they don't provide the MD5 checksum one has to download the archive, confirm the SHA checksum matches, then check the MD5 with `md5sum`, `md5`, `openssl md5` or the like. For example, `md5sum ruby-2.2.2.tar.bz2` or `md5 -r ruby-2.2.2.tar.bz2` (you'd need to add the double-space between checksum and filename with this one) depending on your system.

**Comment by ferdinandrosario** [comment]
Thanks @havenwood

**Pull request closed without merging**
